[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=80", "setuptools-scm>=8" ]

[project]
name = "descent"
description = "Differentiably compute energies of molecules using SMIRNOFF force fields."
readme = "README.md"
license = { text = "MIT" }
authors = [ { name = "Simon Boothroyd" } ]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]
dynamic = [ "version" ]

[tool.setuptools]
packages.find.include = [ "descent*" ]

[tool.setuptools_scm]

[tool.ruff]
extend-include = [ "*.ipynb" ]
lint.select = [ "B", "B9", "C", "E", "F", "W" ]
lint.ignore = [ "C901" ]
lint.pydocstyle.convention = "google"

[tool.mypy]
exclude = "descent/tests/"
ignore_missing_imports = true
python_version = "3.12"
warn_unused_ignores = true
allow_redefinition = true
disable_error_code = [ "arg-type", "assignment", "union-attr" ]  # TODO: Try to remove some of these
plugins = "pydantic.mypy"
warn_incomplete_stub = true
warn_unused_configs = true
overrides = [ { module = [
    "datasets",
    "openff.toolkit.*",
    "rdkit",
  ] } ]
show_error_codes = true

[tool.coverage]
run.omit = [ "**/tests/*" ]
report.exclude_lines = [
  "@overload",
  "if __name__ = .__main__.:",
  "if TYPE_CHECKING:",
  "if typing.TYPE_CHECKING:",
  "pragma: no cover",
  "raise NotImplementedError",
]
