name: descent

channels:
  - conda-forge

dependencies:

  - python >=3.10
  - pip

  # Core packages
  - smee-base >=0.10.0

  - pytorch
  - pyarrow
  - datasets

  - pydantic

  ### Levenberg Marquardt
  - scipy

  # Optional packages
  - rdkit
  - matplotlib-base
  - panel

  # Examples
  - jupyter
  - nbconvert

  # Training
#  - ray-default
  - tensorboard
  - tensorboardX

  # Dev / Testing
  - rdkit
  - uncertainties

  - versioneer

  - pre-commit
  - ruff
  - nbqa

  - pytest
  - pytest-cov
  - pytest-mock

  - codecov

  # Docs
  - mkdocs
  - mkdocs-material
  - mkdocs-gen-files
  - mkdocs-literate-nav
  - mkdocstrings
  - mkdocstrings-python >=1.10.8
  - griffe-pydantic
  - black
  - mike
